version: 2.1

defaults: &defaults
  working_directory: ~/axe-rule-help

unix_box: &unix_box
  docker:
    - image: cimg/node:16.14

restore_dependency_cache_unix: &restore_dependency_cache_unix
  restore_cache:
    keys:
      - v1-cache-unix-{{ checksum "package-lock.json" }}
      - v1-cache-unix-

jobs:
  # Fetch and cache dependencies.
  dependencies_unix:
    <<: *defaults
    <<: *unix_box
    steps:
      - checkout
      - <<: *restore_dependency_cache_unix
      - run: npm ci
      - save_cache:
          key: v1-cache-unix-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  # Run ESLINT
  lint:
    <<: *defaults
    <<: *unix_box
    steps:
      - checkout
      - <<: *restore_dependency_cache_unix
      - run: npm run lint

  # Run tests
  test:
    <<: *defaults
    <<: *unix_box
    steps:
      - checkout
      - <<: *restore_dependency_cache_unix
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - dependencies_unix
      - lint:
          requires:
            - dependencies_unix
      - test:
          requires:
            - lint